[meta]
title = "Home"
description = "This is my website, home to projects and programs, and some of them work!"
author = "jumbledFox"
background = "rainbow"

[[boxes]]
[[boxes.parts]]
kind = "title"
content = "# Hello! :3"

[[boxes.parts]]
kind = "body"
content = """
Hello! I'm jumbledFox, a 16 year old programmer from the UK.
This is my epic website.
"""
# ---------- #
[[boxes]]
[[boxes.parts]]
kind = "body"
content = """
# THINGS I'VE DONE
## *GAMES*
I've made a few games in my time, some more than others.. Here they are in all their glory.

[Swag Weaselz](/games/swag-weaselz) - Made in around a day, this simple scratch game about shooting blocky green enemies is weasel-tastic. Now featuring some epic doom-style box art I drew!

[Trash and Lasers](/games/trash-and-lasers) -  A game about destroying trash in the ocean with lasers! Made for the Polymars [SEAJAM](https://itch.io/jam/seajam).

[Favibird](/games/favibird) - A flappy bird game played in the favicon.
"""
[[boxes.parts]]
kind = "body"
content = """
## *Electronics*
From gizmos to gadgets, I like to tinker. Here are some physical things I've made, more to come in the future.

[The Internet](/projects/the-internet) - My homemade prop of The Internet from The IT Crowd.

[LED Flashing Light Mask](/projects/led-flashing-light-mask) - An eye mask that flashes red light at a user-defined speed and brightness. Made for my mum

## *Other various projects*

[jumbledFont](/projects/jumbledfont) - A neat pixely font I made a while ago.
"""
# ---------- #
[[boxes]]
[[boxes.parts]]
kind = "body"
content = """
# ABOUT ME
Hello!!! You can call me jumbledFox. I program in Rust, Python, and C++, as well as the occasional website overhaul.

I'm only recently learning Rust after a good few years of C++, getting used to it is going to take some time!

My favourite bands are probably The Police and Genesis currently, however recently I've been getting into artists like 100 gecs, and I really love them!!!!

I love Half-Life, CS:GO, and Portal, they're some of my favourite games and huge inspirations in my projects :3

I've been having cold showers for <span id=\"coldshowers\">---</span> days now

<script>
document.addEventListener("DOMContentLoaded", () => {
    // Live cold shower update
    var date1 = new Date("10/22/2021");
    var date2 = new Date();

    var Difference_In_Time = date2.getTime() - date1.getTime();

    var Difference_In_Days = Difference_In_Time / (1000 * 3600 * 24);

    document.getElementById("coldshowers").innerHTML = Math.floor(Difference_In_Days) + " days";
});
</script>

My discord is <r>jumbledFox#7214</r>, feel free to add me!

[Github](https://github.com/jumbledFox)
"""
[[boxes.parts]]
kind = "body"
content = """
# ABOUT THIS WEBSITE
This website was generated with my static website generator <a href=\"https://github.com/jumbledFox/Sting\">Sting</a>, named after Sting of 'The Police' fame.

I designed it myself, it uses the css mix-blend-mode multiply to make anything the background image, which I think looks really nice!!
"""