[meta]
title = "404"
description = "Page Not Found"
author = "jumbledFox"
background = "missing"

[[boxes]]
[[boxes.parts]]
kind = "title"
content = "# 404"

[[boxes.parts]]
kind = "body"
content = """
Page not found!!

Sorry..!
"""